version: '3.3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_cont
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./static:/static/root/static
      - ./config/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./config/nginx/sites-available:/etc/nginx/sites-available
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - web
  web:
    build: .
    container_name: web_cont
    restart: always
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py collectstatic <<< yes && gunicorn -b 0.0.0.0:8000 --workers=4 webelopers_scoreboard.wsgi"
    volumes:
      - ./static:/root/hardwar/static
    depends_on:
      - db
    expose:
      - 8000
  db:
    image: postgres:latest
    container_name: db_cont
    restart: always
    volumes:
      - ../Database:/var/lib/postgresql/data
      - ../Database_backup:/Database_backup
